name = "PkgDebugPkgB"
uuid = "0964fe9f-8940-4aac-95dd-e092a7137023"
authors = ["Michael Goerz <goerz@stanford.edu>"]
version = "0.1.0"

[deps]
PkgDebugPkgA = "621084bb-f1a1-45e5-9057-22828cfd6aaa"

[compat]
PkgDebugPkgA = "0.1.0"
